/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reloj;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author SOIB1A07
 */
public class Carcasa extends javax.swing.JFrame {

    public int activador = 0;
    private int hora = 0;
    private int minuto = 0;
    public int datohora = 0;
    public int datominuto = 0;

    public void sethora(int suenahora) {
        this.hora = suenahora;
    }

    public void setminuto(int suenaminuto) {
        this.minuto = suenaminuto;
    }

    public int gethora() {
        return hora;
    }

    public int getminuto() {
        return minuto;
    }

    public JLabel getLminutos() {
        return Lminutos;
    }

    public JLabel getLsegundos() {
        return Lsegundos;
    }

    public void fijarAlarma() {
        if (activador % 2 == 0) {
            jSliderhora.setEnabled(true);
            jSliderminuto.setEnabled(true);
            Lalarmaminutos.setEnabled(true);
            Labelseparacion.setEnabled(true);
            activador++;

        } else {
            jSliderhora.setEnabled(false);
            jSliderminuto.setEnabled(false);
             Lalarmahora.setEnabled(false);
            Lalarmaminutos.setEnabled(false);
            Labelseparacion.setEnabled(false);
            activador++;
            // setSuenahora(Lalarmahora.getText());
            //  setSuenaminuto(Lalarmaminutos.getText());
            System.out.println("datos pillados " + datohora);
            System.out.println("datos pillados " + datominuto);

        }

    }

    /**
     * Creates new form Carcasa
     */
    public Carcasa() {
        initComponents();
        try {
            setIconImage(new ImageIcon(getClass().getResource("../imagenes/superlopez.png")).getImage());
        } catch (Exception ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbarraminutos1 = new javax.swing.JLabel();
        barraHoras = new javax.swing.JProgressBar();
        Lhora = new javax.swing.JLabel();
        Lminutos = new javax.swing.JLabel();
        Lsegundos = new javax.swing.JLabel();
        barraMinutos = new javax.swing.JProgressBar();
        barraSegundos = new javax.swing.JProgressBar();
        insertaHora = new javax.swing.JTextField();
        Buttonalarma = new javax.swing.JToggleButton();
        jSliderhora = new javax.swing.JSlider();
        jSliderminuto = new javax.swing.JSlider();
        Lalarmaminutos = new javax.swing.JLabel();
        Labelseparacion = new javax.swing.JLabel();
        jRadiofijar = new javax.swing.JRadioButton();
        jButtoniracrono = new javax.swing.JButton();
        Lalarmahora = new javax.swing.JLabel();

        Lbarraminutos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Lbarraminutos1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setLocation(new java.awt.Point(400, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        barraHoras.setMaximum(24);

        Lhora.setText("HORA");

        Lminutos.setText("MINUTOS");

        Lsegundos.setText("SEGUNDOS");

        barraMinutos.setMaximum(60);

        barraSegundos.setMaximum(60);

        insertaHora.setEditable(false);
        insertaHora.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        insertaHora.setText("00:00:00");
        insertaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaHoraActionPerformed(evt);
            }
        });

        Buttonalarma.setText("ALARMA");
        Buttonalarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonalarmaActionPerformed(evt);
            }
        });

        jSliderhora.setMajorTickSpacing(1);
        jSliderhora.setMaximum(23);
        jSliderhora.setMinorTickSpacing(1);
        jSliderhora.setPaintLabels(true);
        jSliderhora.setPaintTicks(true);
        jSliderhora.setValue(0);
        jSliderhora.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderhoraStateChanged(evt);
            }
        });
        jSliderhora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSliderhoraMouseClicked(evt);
            }
        });

        jSliderminuto.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jSliderminuto.setMajorTickSpacing(5);
        jSliderminuto.setMaximum(59);
        jSliderminuto.setMinorTickSpacing(1);
        jSliderminuto.setPaintLabels(true);
        jSliderminuto.setPaintTicks(true);
        jSliderminuto.setSnapToTicks(true);
        jSliderminuto.setValue(30);
        jSliderminuto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderminutoStateChanged(evt);
            }
        });

        Lalarmaminutos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        Labelseparacion.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Labelseparacion.setText(":");

        jRadiofijar.setText("fijar");
        jRadiofijar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadiofijarStateChanged(evt);
            }
        });
        jRadiofijar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadiofijarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jRadiofijarMouseEntered(evt);
            }
        });
        jRadiofijar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadiofijarActionPerformed(evt);
            }
        });

        jButtoniracrono.setText("CRONO");
        jButtoniracrono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniracronoActionPerformed(evt);
            }
        });

        Lalarmahora.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lhora)
                            .addComponent(Lminutos)
                            .addComponent(Lsegundos))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barraHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(insertaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buttonalarma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtoniracrono)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lalarmahora, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Labelseparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lalarmaminutos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadiofijar)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jSliderhora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSliderminuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertaHora)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lhora)
                            .addComponent(barraHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lminutos)
                            .addComponent(barraMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lsegundos)
                            .addComponent(barraSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonalarma)
                    .addComponent(jButtoniracrono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSliderminuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Labelseparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(Lalarmaminutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadiofijar))
                    .addComponent(Lalarmahora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaHoraActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /**
         * La clase Timer es un secuenciador. con él, llamamos a un método en un
         * periodo determinado
         *
         * @param 1000: valor en milesimas, de la periocidad de activación del
         * metodo
         * @java.awt.event.ActionListener(): Interface que obliga a instanciar
         * un objeto en donde se inscribirá el método a ejecutar.
         */

        Timer iniciarReloj = new Timer(1000, new java.awt.event.ActionListener() {
            /**
             *
             * @param e enlaza para ejecutar la acción del método asociado a la
             * Interface ActionListener. sería algo así, como el "click" del
             * ratón.
             */

            public void actionPerformed(ActionEvent e) {
                Calendar calendario = new GregorianCalendar();
                int segundos;
                sethora(calendario.get(Calendar.HOUR_OF_DAY));
                //hora = calendario.get(Calendar.HOUR_OF_DAY);
                setminuto(calendario.get(Calendar.MINUTE));
                // minutos = calendario.get(Calendar.MINUTE);
                segundos = calendario.get(Calendar.SECOND);

                insertaHora.setText(gethora() + ":" + getminuto() + ":" + segundos);
                barraHoras.setValue(gethora());
                barraMinutos.setValue(getminuto());
                barraSegundos.setValue(segundos);
                if (gethora()==datohora && getminuto()==datominuto) {
                    JOptionPane.showMessageDialog(null, "La alarma está sonando");
                    datohora=0;
                    datominuto=0;
                }
                    

            }
        });
        iniciarReloj.start();
        Labelseparacion.setEnabled(false);
        jSliderhora.setEnabled(false);
        jSliderminuto.setEnabled(false);
        Lalarmaminutos.setEnabled(false);
        jRadiofijar.setEnabled(false);
        
        
        
    }//GEN-LAST:event_formWindowActivated

    private void ButtonalarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonalarmaActionPerformed
        // TODO add your handling code here:
        if (activador % 2 == 0) {
            jSliderhora.setEnabled(true);
            jSliderminuto.setEnabled(true);
            Lalarmaminutos.setEnabled(true);
            Lalarmahora.setEnabled(true);
            Labelseparacion.setEnabled(true);
            jRadiofijar.setEnabled(true);
        } else {
            jSliderhora.setEnabled(false);
            jSliderminuto.setEnabled(false);
            Lalarmaminutos.setEnabled(false);
            Labelseparacion.setEnabled(false);
            Lalarmahora.setEnabled(false);
            jRadiofijar.setEnabled(false);
        }
        activador++;


    }//GEN-LAST:event_ButtonalarmaActionPerformed

    private void jSliderhoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSliderhoraMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jSliderhoraMouseClicked

    private void jSliderhoraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderhoraStateChanged
        // TODO add your handling code here:

        String horastring = "";
        datohora = jSliderhora.getValue();
        horastring = Integer.toString(datohora);
        Lalarmahora.setText(""+horastring);
    }//GEN-LAST:event_jSliderhoraStateChanged

    private void jSliderminutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderminutoStateChanged
        // TODO add your handling code here:

        String minutostring = "";
        datominuto = jSliderminuto.getValue();
        minutostring = Integer.toString(datominuto);
        Lalarmaminutos.setText(minutostring);
    }//GEN-LAST:event_jSliderminutoStateChanged

    private void jRadiofijarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadiofijarStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadiofijarStateChanged

    private void jRadiofijarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadiofijarMouseClicked
        // TODO add your handling code here:
        fijarAlarma();
     /*    Reloj reloj = new Reloj();
        Timer alarma = new Timer(1000, reloj);
         alarma.start();/*

        /* if (activador % 2 == 0) {jSliderhora.setEnabled(true);
            jSliderminuto.setEnabled(true);
            Lalarmaminutos.setEnabled(true);
            Lalarmahora.setEnabled(true);
            activador++;
            
        } else {jSliderhora.setEnabled(false);
            jSliderminuto.setEnabled(false);
            Lalarmaminutos.setEnabled(false);
            Lalarmahora.setEnabled(false);
            activador++;
            setSuenahora(Lalarmahora.getText());
            setSuenaminuto(Lalarmaminutos.getText());
            System.out.println("datos pillados "+getSuenahora());
            System.out.println("datos pillados "+getSuenaminuto());
            Reloj reloj = new Reloj();
        Timer alarma = new Timer(1000, reloj);
        alarma.start();
            
        }*/

    }//GEN-LAST:event_jRadiofijarMouseClicked

    private void jButtoniracronoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniracronoActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronometro().setVisible(true);
                
            }
        });
    }//GEN-LAST:event_jButtoniracronoActionPerformed

    private void jRadiofijarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadiofijarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadiofijarActionPerformed

    private void jRadiofijarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadiofijarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadiofijarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carcasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carcasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carcasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carcasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carcasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Buttonalarma;
    private javax.swing.JLabel Labelseparacion;
    private javax.swing.JLabel Lalarmahora;
    private javax.swing.JLabel Lalarmaminutos;
    private javax.swing.JLabel Lbarraminutos1;
    private javax.swing.JLabel Lhora;
    private javax.swing.JLabel Lminutos;
    private javax.swing.JLabel Lsegundos;
    private javax.swing.JProgressBar barraHoras;
    private javax.swing.JProgressBar barraMinutos;
    private javax.swing.JProgressBar barraSegundos;
    private javax.swing.JTextField insertaHora;
    private javax.swing.JButton jButtoniracrono;
    private javax.swing.JRadioButton jRadiofijar;
    private javax.swing.JSlider jSliderhora;
    private javax.swing.JSlider jSliderminuto;
    // End of variables declaration//GEN-END:variables
}
