/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reloj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author SOIB1A07
 */
public class Cronometro extends javax.swing.JFrame {

    public Icon superlopez = new ImageIcon(getClass().getResource("/imagenes/superlopez.png"));
    public Icon iconlopez = new ImageIcon(getClass().getResource("/imagenes/iconolopez.png"));

    public int centesimasatras;
    public int segundosatras;
    public int minutoatras;
    public int inout;

    int segundos = 0;
    int minutos = 0;
    int centesimas = 0;
    Timer segundero;
    Timer minutero;
    Timer centesimero;
    Timer temporizador;

    int[] numeros = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 00};

    public JLabel getjLabelcronocentesimas() {
        return jLabelcronocentesimas;
    }

    public void setjLabelcronocentesimas(JLabel jLabelcronocentesimas) {
        this.jLabelcronocentesimas = jLabelcronocentesimas;
    }

    public JLabel getjLabelcronominutos() {
        return jLabelcronominutos;
    }

    public void setjLabelcronominutos(JLabel jLabelcronominutos) {
        this.jLabelcronominutos = jLabelcronominutos;
    }

    public JLabel getjLabelcronosegundos() {
        return jLabelcronosegundos;
    }

    public void setjLabelcronosegundos(JLabel jLabelcronosegundos) {
        this.jLabelcronosegundos = jLabelcronosegundos;
    }

    /**
     * Creates new form Cronometro
     */
    public Cronometro() {
        initComponents();
        try {
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/superlopez.png")).getImage());
        } catch (Exception ex) {

        }
    }

    public void cuentaAtras() {

        if (temporizador == null) {

            temporizador = new Timer(100, new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {

                    if (centesimas > 0) {
                        centesimas--;
                    } else {
                        if (segundos == 0 && minutos == 0 && centesimas == 0) {
                            temporizador.stop();
                            JOptionPane.showMessageDialog(null, "Is the final Countdown..., tiroriro.. tirorirorii...",
                                    "BIB, BIB, BIB, BIB, BIB, BIB, BIB, BIB, BIB, BIB,", 1, superlopez);
                        } else if (segundos > 0) {
                            segundos--;
                            centesimas = 9;
                        } else if (minutos > 0) {
                            minutos--;
                            segundos = 59;
                            centesimas = 9;
                        }
                    }
                    if (segundos < 10) {
                        System.out.println("Control control!!!!");
                          jLabelcronominutos.setText("0" + String.valueOf(minutos));
                          jLabelcronosegundos.setText("0"+ String.valueOf(segundos));
                          jLabelcronocentesimas.setText(String.valueOf(centesimas)+"0");

                    } else {
                        jLabelcronominutos.setText("0" + String.valueOf(minutos));
                        jLabelcronosegundos.setText(String.valueOf(segundos));
                        jLabelcronocentesimas.setText(String.valueOf(centesimas) + "0");
                    }
                }
            });

        }
        temporizador.setRepeats(true);
        temporizador.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buttonrunning = new javax.swing.JButton();
        jLabelcronosegundos = new javax.swing.JLabel();
        jLabelcronocentesimas = new javax.swing.JLabel();
        jLabelcronominutos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Buttonreiniciar = new javax.swing.JButton();
        Bottonsetting = new javax.swing.JButton();
        Spinnerminutos = new javax.swing.JSpinner();
        Spinnercentesimas = new javax.swing.JSpinner();
        Spinnersegundos = new javax.swing.JSpinner();
        Buttoncountdown = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        jButtonstop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(950, 200));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Buttonrunning.setFont(new java.awt.Font("Palatino Linotype", 1, 10)); // NOI18N
        Buttonrunning.setText("RUNNING");
        Buttonrunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonrunningActionPerformed(evt);
            }
        });

        jLabelcronosegundos.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabelcronosegundos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelcronosegundos.setText("00");

        jLabelcronocentesimas.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabelcronocentesimas.setForeground(new java.awt.Color(255, 0, 0));
        jLabelcronocentesimas.setText("00");

        jLabelcronominutos.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabelcronominutos.setText("00");

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabel1.setText(":");

        jLabel2.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 48)); // NOI18N
        jLabel2.setText(":");

        Buttonreiniciar.setFont(new java.awt.Font("Palatino Linotype", 1, 10)); // NOI18N
        Buttonreiniciar.setText("REINICIAR");
        Buttonreiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonreiniciarActionPerformed(evt);
            }
        });

        Bottonsetting.setFont(new java.awt.Font("Palatino Linotype", 1, 10)); // NOI18N
        Bottonsetting.setText("SETTING");
        Bottonsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonsettingActionPerformed(evt);
            }
        });

        Buttoncountdown.setText("COUNTDOWN");
        Buttoncountdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtoncountdownActionPerformed(evt);
            }
        });

        mensaje.setText("vuelva a tocar si desea anotar un tiempo");
        mensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mensaje.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        mensaje.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jButtonstop.setText("STOP");
        jButtonstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(Spinnerminutos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(63, 63, 63))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabelcronominutos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Buttonrunning)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelcronosegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonstop)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(Spinnersegundos)))
                                        .addGap(47, 47, 47))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bottonsetting, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelcronocentesimas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Buttoncountdown)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Buttonreiniciar)
                                    .addComponent(Spinnercentesimas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcronosegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcronocentesimas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcronominutos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Spinnerminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinnercentesimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Spinnersegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttonreiniciar)
                    .addComponent(Buttonrunning)
                    .addComponent(jButtonstop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buttoncountdown)
                    .addComponent(Bottonsetting))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonrunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonrunningActionPerformed
        // TODO add your handling code here:
        mensaje.setEnabled(true);
        if (segundero == null && minutero == null && centesimero == null) {

            centesimero = new Timer(100, new ActionListener() {
                /**
                 *
                 * @param e enlaza para ejecutar la acción del método asociado a
                 * la Interface ActionListener. la acción a permutar.
                 *
                 */

                public void actionPerformed(ActionEvent e) {

                    jLabelcronocentesimas.setText(String.valueOf("0" + centesimas));
                    centesimas++;

                    if (centesimas == 9) {
                        centesimas = 0;
                    }
                }

            });

            segundero = new Timer(1000, new ActionListener() {
                /**
                 *
                 * @param e enlaza para ejecutar la acción del método asociado a
                 * la Interface ActionListener. la acción a permutar.
                 *
                 */

                public void actionPerformed(ActionEvent e) {

                    if (segundos < 9) {
                        jLabelcronosegundos.setText(String.valueOf("0" + numeros[segundos]));
                        segundos++;
                    } else {
                        jLabelcronosegundos.setText(String.valueOf(numeros[segundos]));
                        segundos++;
                        if (segundos == 60) {
                            segundos = 0;
                        }
                    }

                }

            });

            minutero = new Timer(60000, new ActionListener() {
                /**
                 *
                 * @param e enlaza para ejecutar la acción del método asociado a
                 * la Interface ActionListener. la acción a permutar.
                 *
                 */

                public void actionPerformed(ActionEvent e) {

                    jLabelcronominutos.setText("0" + String.valueOf(minutos));
                    minutos++;

                }

            });

        }
        if (segundero.isRunning()) {
            jLabelcronocentesimas.setText(String.valueOf(centesimas));
            jLabelcronosegundos.setText(String.valueOf(numeros[segundos]));
            jLabelcronominutos.setText("0" + String.valueOf(minutos));
            JOptionPane.showMessageDialog(null, "0" + minutos + ":"
                    + numeros[segundos] + ":0" + centesimas, "Anote la Marca", 2, iconlopez);

        } else {
            segundero.start();
            minutero.start();
            centesimero.start();
        }

    }//GEN-LAST:event_ButtonrunningActionPerformed

    private void ButtonreiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonreiniciarActionPerformed
        // TODO add your handling code here:
        mensaje.setEnabled(false);
        if (segundero != null) {
            segundero.stop();
            minutero.stop();
            centesimero.stop();
            jLabelcronominutos.setText("00");
            jLabelcronosegundos.setText("00");
            jLabelcronocentesimas.setText("00");
            minutos = 0;
            segundos = 0;
            centesimas = 0;

        } else {
            temporizador.stop();

            minutos = 0;
            segundos = 0;
            centesimas = 0;
            jLabelcronominutos.setText("0" + String.valueOf(minutos));
            jLabelcronosegundos.setText("0" + String.valueOf(segundos));
            jLabelcronocentesimas.setText("0" + String.valueOf(centesimas));
        }
    }//GEN-LAST:event_ButtonreiniciarActionPerformed

    private void BottonsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonsettingActionPerformed
        // TODO add your handling code here:
        Buttoncountdown.setEnabled(true);
        if (segundero != null) {
            segundero.stop();
            minutero.stop();
            centesimero.stop();
        }

        minutos = (int) Spinnerminutos.getValue();
        segundos = (int) Spinnersegundos.getValue();
        centesimas = (int) Spinnercentesimas.getValue();
        System.out.println("lo has programado esto: ? " + minutos + segundos + centesimas);
        jLabelcronominutos.setText("0" + String.valueOf(minutos));
        jLabelcronosegundos.setText(String.valueOf(segundos));
        jLabelcronocentesimas.setText("0" + String.valueOf(centesimas));


    }//GEN-LAST:event_BottonsettingActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mensaje.setEnabled(false);
        Buttoncountdown.setEnabled(false);
        Spinnerminutos.setEnabled(true);
        Spinnersegundos.setEnabled(true);
        Spinnercentesimas.setEnabled(true);
        jLabelcronominutos.setText("0" + String.valueOf(minutos));
        jLabelcronosegundos.setText("0" + String.valueOf(segundos));
        jLabelcronocentesimas.setText("0" + String.valueOf(centesimas));
    }//GEN-LAST:event_formWindowOpened

    private void ButtoncountdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtoncountdownActionPerformed
        // TODO add your handling code here:
        jLabelcronominutos.setText("0" + String.valueOf(minutos));
        jLabelcronosegundos.setText("0" + String.valueOf(segundos));
        jLabelcronocentesimas.setText("0" + String.valueOf(centesimas));

        cuentaAtras();
        Buttoncountdown.setEnabled(false);

    }//GEN-LAST:event_ButtoncountdownActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:


    }//GEN-LAST:event_formWindowClosed

    private void jButtonstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstopActionPerformed
        // TODO add your handling code here:
        segundero.stop();
            minutero.stop();
            centesimero.stop();
    }//GEN-LAST:event_jButtonstopActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bottonsetting;
    private javax.swing.JButton Buttoncountdown;
    private javax.swing.JButton Buttonreiniciar;
    private javax.swing.JButton Buttonrunning;
    private javax.swing.JSpinner Spinnercentesimas;
    private javax.swing.JSpinner Spinnerminutos;
    private javax.swing.JSpinner Spinnersegundos;
    private javax.swing.JButton jButtonstop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelcronocentesimas;
    private javax.swing.JLabel jLabelcronominutos;
    private javax.swing.JLabel jLabelcronosegundos;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables

}
