
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SOIB1A07
 */
public class Euricosaperras extends javax.swing.JFrame {
    
    DecimalFormat df=new DecimalFormat ("0.00");
    

    /**
     * Creates new form Euricosaperras
     */
    public Euricosaperras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextcantidad = new javax.swing.JTextField();
        jRadioPesetas = new javax.swing.JRadioButton();
        jRadioEuros = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextresultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBcalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("VALOR:");

        jTextcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcantidadActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioPesetas);
        jRadioPesetas.setText("a Pesetas");
        jRadioPesetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioPesetasMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRadioEuros);
        jRadioEuros.setText(" a Euros");
        jRadioEuros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioEurosMouseClicked(evt);
            }
        });
        jRadioEuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEurosActionPerformed(evt);
            }
        });

        jButton1.setText("borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("RESULTADO");

        jBcalcular.setText("Calcular");
        jBcalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcalcularMouseClicked(evt);
            }
        });
        jBcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextcantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(jTextresultado))
                    .addComponent(jBcalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioEuros)
                    .addComponent(jRadioPesetas))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(jRadioPesetas)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioEuros)
                    .addComponent(jButton1)
                    .addComponent(jBcalcular))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcantidadActionPerformed

    private void jRadioEurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEurosActionPerformed

    private void jRadioPesetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioPesetasMouseClicked
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_jRadioPesetasMouseClicked

    private void jRadioEurosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioEurosMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jRadioEurosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextcantidad.setText("");
        jTextresultado.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcalcularActionPerformed
        // TODO add your handling code here:
       try { if (jRadioEuros.isSelected()) {
              double cantidad=Double.parseDouble(jTextcantidad.getText());
        double resultado=cantidad/166.386;
        jTextresultado.setText(df.format(resultado)+" Euros");
            
        }
        if (jRadioPesetas.isSelected()) {
            double cantidad=Double.parseDouble(jTextcantidad.getText());
        double resultado=cantidad*166.386;
        jTextresultado.setText(df.format(resultado)+" Pesetas");
            
        } 
         }
         catch (IllegalArgumentException e) {
             jTextresultado.setText("Resetee y vuelva a comenzar");
         }
        
    }//GEN-LAST:event_jBcalcularActionPerformed

    private void jBcalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcalcularMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBcalcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Euricosaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Euricosaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Euricosaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Euricosaperras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Euricosaperras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBcalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioEuros;
    private javax.swing.JRadioButton jRadioPesetas;
    private javax.swing.JTextField jTextcantidad;
    private javax.swing.JTextField jTextresultado;
    // End of variables declaration//GEN-END:variables
}
