
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SOIB1A07
 */
public class Usuaris extends javax.swing.JFrame {

    DefaultTableModel modelo;
    String vSQL = new String();
    String[] registro = new String[4];

    /**
     * Creates new form Jprincipal
     */
    public Usuaris() {
        initComponents();
        consultarUsuaris();
    }
    
    public void reinicio() {
        txtdni.setEnabled(true);
        jBactualizar.setEnabled(true);
        jBguardar.setEnabled(true);
         txtdni.setText("");
        txtnombre.setText("");
        txtapellido1.setText("");
        txtapellido2.setText("");
         consultarUsuaris();
    }

    public void consultarUsuaris() {

<<<<<<< HEAD
        String[] titols = {"NIF", "NOMBRE", "1º APELLIDO", "2º APELLIDO"};
=======
        String[] titols = {"NIF", "NOM", "LLINATGE1", "LLINATGE2"};
>>>>>>> mejoras
        modelo = new DefaultTableModel(null, titols);
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        vSQL = "SELECT DNI , Nombre , Apellido1, Apellido2 from usuaris";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                registro[0] = rs.getString("dni");
                registro[1] = rs.getString("nombre");
                registro[2] = rs.getString("Apellido1");
                registro[3] = rs.getString("Apellido2");
                modelo.addRow(registro);

            }

            tblConsulta.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    public void editarUsuaris(String pNif) {

        String[] titols = {"DNI", "NOM", "LLINATGE1", "LLINATGE2"};
        modelo = new DefaultTableModel(null, titols);
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        vSQL = "SELECT DNI, Nombre, Apellido1, Apellido2 from usuaris "
                + "WHERE DNI = '" + pNif + "'";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                txtdni.setText(rs.getString("DNI"));
                txtnombre.setText(rs.getString("Nombre"));
                txtapellido1.setText(rs.getString("Apellido1"));
                txtapellido2.setText(rs.getString("Apellido2"));

            }
            txtdni.setEnabled(false);
            jBguardar.setEnabled(false);

       //     tblConsulta.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    public void mostraUsuaris(String pNif) {

        String[] titols = {"DNI", "NOM", "LLINATGE1", "LLINATGE2"};
        modelo = new DefaultTableModel(null, titols);
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        vSQL = "SELECT DNI, Nombre, Apellido1, Apellido2 from usuaris "
                + "WHERE DNI = '" + pNif + "'";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);

            while (rs.next()) {
                txtdni.setText(rs.getString("DNI"));
                txtnombre.setText(rs.getString("Nombre"));
                txtapellido1.setText(rs.getString("Apellido1"));
                txtapellido2.setText(rs.getString("Apellido2"));

            }
            txtdni.setEnabled(false);
            jBguardar.setEnabled(false);
            txtnombre.setEditable(false);
            txtapellido1.setEditable(false);
            txtapellido2.setEditable(false);
            jBactualizar.setEnabled(false);

            tblConsulta.setModel(modelo);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuEditar = new javax.swing.JPopupMenu();
        iteModificar = new javax.swing.JMenuItem();
        iteEliminar = new javax.swing.JMenuItem();
        jBguardar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        ibdni = new javax.swing.JLabel();
        ibinombre = new javax.swing.JLabel();
        ibiapellido1 = new javax.swing.JLabel();
        ibiapellido2 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        txtapellido2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        jBReiniciar = new javax.swing.JButton();

        iteModificar.setText("Modificar");
        iteModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteModificarActionPerformed(evt);
            }
        });
        mnuEditar.add(iteModificar);

        iteEliminar.setText("Elininar");
        iteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iteEliminarActionPerformed(evt);
            }
        });
        mnuEditar.add(iteEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBactualizar.setText("Confirmar");
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jBsalir.setText("SALIR");
        jBsalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        ibdni.setText("DNI");

        ibinombre.setText("Nombre");

        ibiapellido1.setText("Apellido1");

        ibiapellido2.setText("Apellido2");

        txtapellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellido2ActionPerformed(evt);
            }
        });

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblConsulta.setComponentPopupMenu(mnuEditar);
        jScrollPane1.setViewportView(tblConsulta);

        jBReiniciar.setText("Reiniciar");
        jBReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ibinombre)
                                .addComponent(ibiapellido1)
                                .addComponent(ibiapellido2)
                                .addComponent(ibdni, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtapellido1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtapellido2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBguardar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBactualizar)
                                .addComponent(jBReiniciar))
                            .addGap(30, 30, 30)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBsalir)
                            .addComponent(jBeliminar))
                        .addGap(146, 146, 146)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibdni)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ibinombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibiapellido1)
                    .addComponent(txtapellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibiapellido2)
                    .addComponent(txtapellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBguardar)
                    .addComponent(jBactualizar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBeliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsalir)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellido2ActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        String vNom, vLli1, vNIF, vLli2;
        String vSQL = "";

        vNIF = txtdni.getText();
        vNom = txtnombre.getText();
        vLli1 = txtapellido1.getText();
        vLli2 = txtapellido2.getText();

        vSQL = "INSERT INTO usuaris(DNI , Nombre , Apellido1 , Apellido2) VALUES (? , ? , ? , ?)";

        try {
            PreparedStatement pst = cn.prepareStatement(vSQL);
            pst.setString(1, vNIF);
            pst.setString(2, vNom);
            pst.setString(3, vLli1);

            pst.setString(4, vLli2);
            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Inserción satisfactòria");
                reinicio();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_jBguardarActionPerformed

    private void iteModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteModificarActionPerformed
        // TODO add your handling code here:
        int filaSel;
        String vNif;
        try {
            filaSel = tblConsulta.getSelectedRow();
            if (filaSel == -1) //Vol dir que no s'ha seleccionat cap fila
            {
                JOptionPane.showMessageDialog(null, "no s'ha selecionat cap fila");
            } else {
                modelo = (DefaultTableModel) tblConsulta.getModel(); // Obtenim el model de la taula tblConsulta imprescindible per manejar-la
                vNif = (String) modelo.getValueAt(filaSel, 0); //Gravam el valor del DNI, que és la columna 0 de la fila seleccionada
                editarUsuaris(vNif);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }


    }//GEN-LAST:event_iteModificarActionPerformed

    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBactualizarActionPerformed
        // TODO add your handling code here:
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        String vNom, vLli1, vNif, vLli2;
        String vSQL = "";
        vNif = txtdni.getText();
        vNom = txtnombre.getText();
        vLli1 = txtapellido1.getText();
        vLli2 = txtapellido2.getText();
        vSQL = "UPDATE usuaris SET Nombre = ? , Apellido1 = ? , Apellido2 = ? WHERE DNI = '" + vNif + "'";

        try {
            PreparedStatement pst = cn.prepareStatement(vSQL);
            pst.setString(1, vNom);
            pst.setString(2, vLli1);
            pst.setString(3, vLli2);
            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Modificaió satisfactòria");
                reinicio();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }

    }//GEN-LAST:event_jBactualizarActionPerformed

    private void iteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iteEliminarActionPerformed
        // TODO add your handling code here:
        int filaSel;
        String vNif;
        try {
            filaSel = tblConsulta.getSelectedRow();
            if (filaSel == -1) //Vol dir que no s'ha seleccionat cap fila
            {
                JOptionPane.showMessageDialog(null, "no s'ha selecionat cap fila");
            } else {
                modelo = (DefaultTableModel) tblConsulta.getModel(); // Obtenim el model de la taula tblConsulta imprescindible per manejar-la
                vNif = (String) modelo.getValueAt(filaSel, 0); //Gravam el valor del DNI, que és la columna 0 de la fila seleccionada
                mostraUsuaris(vNif);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_iteEliminarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:

       
        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();
        String vSQL = "";
        String vNif = txtdni.getText();
        vSQL = "DELETE from usuaris WHERE DNI = '" + vNif + "'";
        try {
            PreparedStatement pst = cn.prepareStatement(vSQL);
            int n = pst.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "Eliminació satisfactòria");
                reinicio();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReiniciarActionPerformed
        // TODO add your handling code here:
         txtdni.setEnabled(true);
        jBactualizar.setEnabled(true);
        jBguardar.setEnabled(true);
        txtdni.setText("");
        txtnombre.setText("");
        txtapellido1.setText("");
        txtapellido2.setText("");
         consultarUsuaris();
    }//GEN-LAST:event_jBReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ibdni;
    private javax.swing.JLabel ibiapellido1;
    private javax.swing.JLabel ibiapellido2;
    private javax.swing.JLabel ibinombre;
    private javax.swing.JMenuItem iteEliminar;
    private javax.swing.JMenuItem iteModificar;
    private javax.swing.JButton jBReiniciar;
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu mnuEditar;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtapellido2;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
