
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author SOIB1A07
 */
public class tresenRaya extends javax.swing.JFrame {

    static int mododejuego = 0;
    int x = 0;
    int y = 0;
    int turno = 0;

    public void setTurno(int turno) {
        this.turno = turno;
    }

    Juegotresrayas partida = new Juegotresrayas();
    String[][] matriz = {{"", "", ""},
    {"", "", ""}, {"", "", ""}};
    String[][] matriz2 = {{"", "", ""},
    {"", "", ""}, {"", "", ""}};

    /**
     * Creates new form tresenRaya
     */
    public tresenRaya() {
        initComponents();
    }

    public String getvalueTable(int x, int y) {
        String valor = (String) tabla.getValueAt(x, y);
        return valor;
    }

    public void setvalueTable(int x, int y) {
        tabla.setValueAt("O", x, y);

    }

    public void contraMaquina() {
        int[] posicion = new int[2];
        int x = 0;
        int y = 0;
        
        x = tabla.getSelectedRow();
        y = tabla.getSelectedColumn();
        tabla.setValueAt("X", x, y);
        matriz[x][y] = "X";
        turno++;
        
        matriz2=Juegotresrayas.copiarmatriz(matriz);
        partida.defensa(matriz);
        if (matriz2==matriz) {
            posicion = partida.colocarficha(matriz);
        tabla.setValueAt("O", posicion[0], posicion[1]);
        }
        Juegotresrayas.imprimirmatriz(matriz);
        turno++;
        if (partida.quienGana(matriz)) {
            mensajes.setText("Demostrada mi superioridad: GANÉ");
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Revancha?", "GAME OVER", 2);
            if (respuesta == 0) {
                reiniciar();
            } else {
                System.exit(0);
            }
        }

        if (turno == 9) {
            mensajes.setText("TABLAS");
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Revancha?", "GAME OVER", 2);
            if (respuesta == 0) {
                reiniciar();
            } else {
                System.exit(0);
            }

        }
        

    }

    public void reiniciar() {
        setTurno(0);
        mensajes.setText("");
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                tabla.setValueAt("", i, j);

            }
        }
        matriz = partida.inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JTable();
        BStart = new javax.swing.JButton();
        mensajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabla.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabla.setRowHeight(90);
        tabla.setRowMargin(5);
        tabla.setTableHeader(null);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });

        BStart.setText("START");
        BStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BStartMousePressed(evt);
            }
        });
        BStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(BStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BStart))
                .addGap(18, 18, 18)
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        // TODO add your handling code here:

        if (mododejuego == 1) {
            contraMaquina();
        }

        mensajes.setText("JUGADOR 2");

        if (turno % 2 == 0) {

            x = tabla.getSelectedRow();
            y = tabla.getSelectedColumn();
            tabla.setValueAt("   X", x, y);
            matriz[x][y] = "X";
            turno++;
         
        } else {
            mensajes.setText("JUGADOR 1");
            x = tabla.getSelectedRow();
            y = tabla.getSelectedColumn();
            tabla.setValueAt("   O", x, y);
            matriz[x][y] = "O";
            turno++;
            

        }
        if (partida.quienGana(matriz)) {
            mensajes.setText("FELICIDADES, HAS GANADO");
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Revancha?", "GAME OVER", 2);
            if (respuesta == 0) {
                reiniciar();
            } else {
                System.exit(0);
            }
        }

        if (turno == 9) {
            mensajes.setText("TABLAS");
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Revancha?", "GAME OVER", 2);
            if (respuesta == 0) {
                reiniciar();
            } else {
                System.exit(0);
            }

        }

    }//GEN-LAST:event_tablaMousePressed

    private void BStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStartActionPerformed
        // TODO add your handling code here:
        setTurno(0);
        mensajes.setText("");
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                tabla.setValueAt("", i, j);

            }
        }
        matriz = partida.inicializar();


    }//GEN-LAST:event_BStartActionPerformed

    private void BStartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BStartMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_BStartMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        mododejuego = JOptionPane.showConfirmDialog(null,
                "¿Dos jugadores?", "MODO DE JUEGO",
                JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tresenRaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BStart;
    private javax.swing.JLabel mensajes;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
